name: Package

on:
  push:
    branches: [main, develop]
    tags:
      - "v2.*"
  pull_request:
    branches: [main, develop]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    name: Build wheel distribution
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "pypy-3.10"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update build dependencies
        run: python -m pip install -U pip wheel setuptools

      - name: Build wheel distribution
        run: python -m build

      - name: Store built wheel
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  build-sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Update build dependencies
        run: python -m pip install -U pip wheel setuptools

      - name: Build source distribution
        run: python -m build

      - name: Store source distribution
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  test-sdist:
    runs-on: ubuntu-latest
    name: Test source distribution
    needs:
      - build-sdist
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Download source distribution
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Install source distribution
        run: python -m pip install dist/fs-*.tar.gz

      - name: Remove source code
        run: rm -rvd fs

      - name: Install test requirements
        run: python -m pip install -r tests/requirements.txt

      - name: Test installed package
        run: python -m unittest discover -vv

  test-wheel:
    runs-on: ubuntu-latest
    name: Test wheel distribution
    needs:
      - build-wheel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Download wheel distribution
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Install wheel distribution
        run: python -m pip install dist/fs-*.whl

      - name: Remove source code
        run: rm -rvd fs

      - name: Install test requirements
        run: python -m pip install -r tests/requirements.txt

      - name: Test installed package
        run: python -m unittest discover -vv

  upload:
    runs-on: ubuntu-latest
    name: Upload
    needs:
      - build-sdist
      - build-wheel
      - test-sdist
      - test-wheel

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Publish distributions to PyPI
        if: startsWith(github.ref, 'refs/tags/v')

        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: false

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Release
    needs: upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release a Changelog
        uses: rasmus-saks/release-a-changelog-action@v1.0.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
